name: GitHub-Profile-Summary-Cards

on:
  create:
  schedule: # execute every 24 hours
    - cron: "0 0 * * *" # Run every day at midnight UTC
  workflow_dispatch:

jobs:
  build: # This must be indented properly under jobs
    runs-on: ubuntu-latest
    name: Generate GitHub Cards
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Generate Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARD_TOKEN }}
        with:
          USERNAME: Mohammad-al-buraiki
