name: GitHub-Profile-Summary-Cards

on:
  create:
  schedule: # execute every 24 hours
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build: # Fixed indentation here
    runs-on: ubuntu-latest
    name: Generate GitHub Cards
    permissions:
      contents: write

    steps:
      - name: Checkout Repository # Added a name for the step
        uses: actions/checkout@v2
      - name: Generate Summary Cards # Added a name for the step
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARD_TOKEN }} # Replace with your actual secret name
        with:
          USERNAME: ${{ github.repository_owner }} # Dynamically gets the repository owner
